- name: Configure instance(s)
  hosts: launched
  remote_user: '{{ec2_remote_user}}'
  gather_facts: True
  become: true
  become_user: root
  vars:
      ansible_python_interpreter: '/usr/bin/python3'
      ufw_rules: "{{firewall_rules}}"
      users: "{{ec2_ssh_users}}"

  roles:
    - { role: server-hardening, tags: [server-hardening], become: True, become_user: root }
    - { role: geth-ethereum, tags: [geth-ethereum] }
    - { role: journald-cloudwatch, tags: [journald-cloudwatch] }
